Cocktails/Areas/AdminPanel/Controllers/CocktailIngredientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CocktailsDatabase;

namespace Cocktails.Areas.AdminPanel.Controllers
{
    public class CocktailIngredientsController : Controller
    {
        private CocktailsDbContext db = new CocktailsDbContext();

        // GET: AdminPanel/CocktailIngredients
        public ActionResult Index()
        {
            var cocktailIngredients = db.CocktailIngredients
                .Include(c => c.Cocktail)
                .Include(c => c.Ingredient);
            return View(cocktailIngredients.ToList());
        }
        
        // GET: AdminPanel/CocktailIngredients/Create
        public ActionResult Create(int? cocktailId)
        {
            if (cocktailId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cocktail cocktail = db.Cocktails.Find(cocktailId);
            if (cocktail == null)
            {
                return HttpNotFound();
            }
            CocktailIngredient cocktailIngredient = new CocktailIngredient()
            {
                CocktailId = cocktail.Id,
                Cocktail = cocktail
            };
            ViewBag.IngredientId = new SelectList(db.Ingredients, "Id", "Name");
            return View(cocktailIngredient);
        }

        // POST: AdminPanel/CocktailIngredients/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CocktailId,IngredientId,Count")] CocktailIngredient cocktailIngredient)
        {
            if (ModelState.IsValid)
            {
                db.CocktailIngredients.Add(cocktailIngredient);
                db.SaveChanges();
                return RedirectToAction("Details", "Cocktails", new { id = cocktailIngredient.CocktailId });
            }

            Cocktail cocktail = db.Cocktails.Find(cocktailIngredient.CocktailId);
            cocktailIngredient.Cocktail = cocktail;

            ViewBag.IngredientId = new SelectList(db.Ingredients, "Id", "Name", cocktailIngredient.IngredientId);
            return View(cocktailIngredient);
        }

        // GET: AdminPanel/CocktailIngredients/Edit/5
        public ActionResult Edit(int? cocktailId, int? ingredientId)
        {
            if (cocktailId == null && ingredientId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CocktailIngredient cocktailIngredient = db.CocktailIngredients
                .Include(ci => ci.Cocktail)
                .Include(ci => ci.Ingredient)
                .FirstOrDefault(ci => ci.CocktailId == cocktailId && ci.IngredientId == ingredientId);
            if (cocktailIngredient == null)
            {
                return HttpNotFound();
            }
            return View(cocktailIngredient);
        }

        // POST: AdminPanel/CocktailIngredients/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CocktailId,IngredientId,Count")] CocktailIngredient cocktailIngredient)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cocktailIngredient).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Cocktails", new { id = cocktailIngredient.CocktailId });
            }

            Cocktail cocktail = db.Cocktails.Find(cocktailIngredient.CocktailId);
            Ingredient ingredient = db.Ingredients.Find(cocktailIngredient.IngredientId);
            cocktailIngredient.Cocktail = cocktail;
            cocktailIngredient.Ingredient = ingredient;
            
            return View(cocktailIngredient);
        }

        // GET: AdminPanel/CocktailIngredients/Delete/5
        public ActionResult Delete(int? cocktailId, int? ingredientId)
        {
            if (cocktailId == null && ingredientId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CocktailIngredient cocktailIngredient = db.CocktailIngredients
                .Include(ci => ci.Cocktail)
                .Include(ci => ci.Ingredient)
                .FirstOrDefault(ci => ci.CocktailId == cocktailId && ci.IngredientId == ingredientId);
            if (cocktailIngredient == null)
            {
                return HttpNotFound();
            }
            return View(cocktailIngredient);
        }

        // POST: AdminPanel/CocktailIngredients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? cocktailId, int? ingredientId)
        {
            CocktailIngredient cocktailIngredient = db.CocktailIngredients.Find(cocktailId, ingredientId);
            db.CocktailIngredients.Remove(cocktailIngredient);
            db.SaveChanges();
            return RedirectToAction("Details", "Cocktails", new { id = cocktailId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Cocktails/Areas/AdminPanel/Views/CocktailIngredients/Create.cshtml
@model CocktailsDatabase.CocktailIngredient

@{
    ViewBag.Title = "Add ingredient for " + Model.Cocktail.Name;
}

<h2>Add ingredient for</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@Model.Cocktail.Name</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CocktailId)

        <div class="form-group">
            @Html.LabelFor(model => model.IngredientId, "IngredientId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IngredientId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IngredientId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Count, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to " + Model.Cocktail.Name, "Details", "Cocktails", new { id = Model.CocktailId })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Cocktails/Areas/AdminPanel/Views/CocktailIngredients/Delete.cshtml
@model CocktailsDatabase.CocktailIngredient

@{
    ViewBag.Title = "Delete " + Model.Ingredient.Name + " from " + Model.Cocktail.Name;
}

<h2>Remove ingredient from cocktail</h2>

<h3>Are you sure you want to remove this ingredient?</h3>
<div>
    <h4>CocktailIngredient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cocktail.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cocktail.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ingredient.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ingredient.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Count)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Count)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to " + Model.Cocktail.Name, "Details", "Cocktails", new { id = Model.CocktailId })
        </div>
    }
</div>

Cocktails/Areas/AdminPanel/Views/CocktailIngredients/Edit.cshtml
@model CocktailsDatabase.CocktailIngredient

@{
    ViewBag.Title = "Edit count of " + Model.Ingredient.Name;
}

<h2>Edit count of</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@Model.Ingredient.Name</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CocktailId)

        @Html.HiddenFor(model => model.IngredientId)

        <div class="form-group">
            @Html.LabelFor(model => model.Count, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to " + Model.Cocktail.Name, "Details", "Cocktails", new { id = Model.CocktailId })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Cocktails/Areas/AdminPanel/Views/CocktailIngredients/Index.cshtml
@model IEnumerable<CocktailsDatabase.CocktailIngredient>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Cocktail.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ingredient.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Count)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Cocktail.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ingredient.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Count)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

Cocktails/Areas/AdminPanel/Views/CocktailIngredients/List.cshtml
@model IEnumerable<CocktailsDatabase.CocktailIngredient>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Cocktail.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ingredient.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Count)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Cocktail.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ingredient.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Count)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", "CocktailIngredients", new { cocktailId = item.CocktailId, ingredientId = item.IngredientId }, null) |
            @Html.ActionLink("Delete", "Delete", "CocktailIngredients", new { cocktailId = item.CocktailId, ingredientId = item.IngredientId }, null)
        </td>
    </tr>
}

</table>